<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = [
            [
                'name' => 'Carlos Rodriguez Martinez',
                'email' => 'carlos.rodriguez@email.com',
                'phone' => '+57 300 123 4567',
                'secondary_phone' => '+57 1 234 5678',
                'document_type' => 'cedula',
                'document_number' => '12345678',
                'address' => 'Carrera 15 #85-20, Chapinero, Bogotá',
                'birth_date' => '1985-03-15',
                'occupation' => 'Ingeniero de Software',
                'notes' => 'Cliente interesado en apartamentos de lujo en zona norte. Presupuesto alto.',
                'interest_level' => 'high',
                'status' => 'activo',
                'preferred_contact_method' => 'whatsapp',
                'last_contact_date' => now()->subDays(3),
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(3),
            ],
            [
                'name' => 'Maria Elena Gutierrez',
                'email' => 'maria.gutierrez@email.com',
                'phone' => '+57 301 987 6543',
                'document_type' => 'cedula',
                'document_number' => '87654321',
                'address' => 'Calle 127 #7-45, Usaquén, Bogotá',
                'birth_date' => '1992-07-22',
                'occupation' => 'Doctora',
                'notes' => 'Busca casa familiar con jardín. Tiene dos hijos pequeños.',
                'interest_level' => 'high',
                'status' => 'prospecto',
                'preferred_contact_method' => 'phone',
                'last_contact_date' => now()->subDays(1),
                'created_at' => now()->subDays(15),
                'updated_at' => now()->subDays(1),
            ],
            [
                'name' => 'Juan Pablo Torres',
                'email' => 'juanp.torres@email.com',
                'phone' => '+57 302 456 7890',
                'document_type' => 'cedula',
                'document_number' => '45678912',
                'address' => 'Avenida 68 #45-67, Engativá, Bogotá',
                'birth_date' => '1988-11-10',
                'occupation' => 'Arquitecto',
                'notes' => 'Interesado en propiedades comerciales para inversión.',
                'interest_level' => 'medium',
                'status' => 'activo',
                'preferred_contact_method' => 'email',
                'last_contact_date' => now()->subDays(7),
                'created_at' => now()->subDays(45),
                'updated_at' => now()->subDays(7),
            ],
            [
                'name' => 'Ana Sofia Herrera',
                'email' => 'anasofia.herrera@email.com',
                'phone' => '+57 303 789 0123',
                'secondary_phone' => '+57 1 345 6789',
                'document_type' => 'cedula_extranjeria',
                'document_number' => 'CE123456789',
                'address' => 'Carrera 11 #93-15, Chicó, Bogotá',
                'birth_date' => '1990-05-18',
                'occupation' => 'Gerente de Marketing',
                'notes' => 'Extranjera recién llegada al país. Necesita apartamento amoblado.',
                'interest_level' => 'high',
                'status' => 'prospecto',
                'preferred_contact_method' => 'both',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(2),
            ],
            [
                'name' => 'Roberto Andres Jimenez',
                'email' => 'roberto.jimenez@email.com',
                'phone' => '+57 304 234 5678',
                'document_type' => 'cedula',
                'document_number' => '78912345',
                'address' => 'Calle 170 #15-30, La Calleja, Bogotá',
                'birth_date' => '1975-12-03',
                'occupation' => 'Empresario',
                'notes' => 'Cliente VIP. Interesado en penthouses y propiedades exclusivas.',
                'interest_level' => 'high',
                'status' => 'activo',
                'preferred_contact_method' => 'phone',
                'last_contact_date' => now()->subDays(2),
                'created_at' => now()->subDays(60),
                'updated_at' => now()->subDays(2),
            ],
            [
                'name' => 'Laura Cristina Morales',
                'email' => 'laura.morales@email.com',
                'phone' => '+57 305 567 8901',
                'document_type' => 'cedula',
                'document_number' => '23456789',
                'address' => 'Transversal 19 #104-20, Santa Barbara, Bogotá',
                'birth_date' => '1987-09-14',
                'occupation' => 'Abogada',
                'notes' => 'Primera compra de vivienda. Necesita asesoría completa.',
                'interest_level' => 'medium',
                'status' => 'prospecto',
                'preferred_contact_method' => 'email',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(5),
            ],
            [
                'name' => 'Diego Fernando Castro',
                'email' => 'diego.castro@email.com',
                'phone' => '+57 306 890 1234',
                'document_type' => 'pasaporte',
                'document_number' => 'PP987654321',
                'address' => 'Carrera 7 #72-35, Zona Rosa, Bogotá',
                'birth_date' => '1983-01-25',
                'occupation' => 'Consultor Internacional',
                'notes' => 'Viaja frecuentemente. Prefiere comunicación por email.',
                'interest_level' => 'low',
                'status' => 'inactivo',
                'preferred_contact_method' => 'email',
                'last_contact_date' => now()->subDays(30),
                'created_at' => now()->subDays(90),
                'updated_at' => now()->subDays(30),
            ],
            [
                'name' => 'Camila Andrea Ruiz',
                'email' => 'camila.ruiz@email.com',
                'phone' => '+57 307 345 6789',
                'secondary_phone' => '+57 1 456 7890',
                'document_type' => 'cedula',
                'document_number' => '34567890',
                'address' => 'Calle 116 #9-15, Santa Barbara, Bogotá',
                'birth_date' => '1995-04-08',
                'occupation' => 'Diseñadora Gráfica',
                'notes' => 'Joven profesional. Busca estudio o apartamento pequeño.',
                'interest_level' => 'medium',
                'status' => 'prospecto',
                'preferred_contact_method' => 'whatsapp',
                'last_contact_date' => now()->subDays(4),
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(4),
            ],
        ];

        foreach ($clients as $clientData) {
            \App\Models\Client::create($clientData);
        }
    }
}
